defaultBaseImage: ghcr.io/distroless/static:latest

builds:
- id: admission-sidecar
  dir: .
  main: ./cmd/admission-sidecar
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  - -tags
  - nostackdriver
  ldflags:
  - -s
  - -w
  - -extldflags "-static"
  - "{{ .Env.LDFLAGS }}"
