# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chainguard-proxy-namespace-rbac
  namespace: chainguard-proxy
rules:
  # Needed to watch and load configuration data.
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "update", "watch"]
