# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chainguard-proxy
  namespace: chainguard-proxy
subjects:
  - kind: ServiceAccount
    name: chainguard-proxy
    namespace: chainguard-proxy
roleRef:
  kind: Role
  name: chainguard-proxy-namespace-rbac
  apiGroup: rbac.authorization.k8s.io
