# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admission-sidecar
  namespace: admission-sidecar
subjects:
  - kind: ServiceAccount
    name: admission-sidecar
    namespace: admission-sidecar
roleRef:
  kind: Role
  name: admission-sidecar-namespace-rbac
  apiGroup: rbac.authorization.k8s.io
