# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  labels:
    app: chainguard-proxy
  name: proxy
  namespace: chainguard-proxy
spec:
  ports:
  - name: http-webhook
    port: 80
    targetPort: 8088
  selector:
    app: chainguard-proxy
