# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: chainguard-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chainguard-proxy
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: chainguard-proxy
    spec:
      serviceAccountName: chainguard-proxy
      containers:
      - name: controller
        image: ko://github.com/chainguard-dev/admission-sidecar/cmd/admission-sidecar
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - name: http-webhook
          containerPort: 8088
        readinessProbe:
          periodSeconds: 1
          httpGet:
            scheme: HTTP
            port: 8088
            httpHeaders:
            - name: k-kubelet-probe
              value: "chainguard-proxy"
        livenessProbe:
          periodSeconds: 1
          failureThreshold: 50
          httpGet:
            scheme: HTTP
            port: 8088
            httpHeaders:
            - name: k-kubelet-probe
              value: "chainguard-proxy"
        env:
        - name: REQUIRE_LABEL
          value: "true"
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_MIN_VERSION
          value: "1.21.0"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: chainguard.dev/admission-sidecar
        - name: PROXY_PORT
          value: "8088"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - all
